# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [ 1, 3, 5 ]
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_reverse = true
sort_dir_first = true

[preview]
max_width = 5120
max_height = 2880
# "nearest", "triangle", "catmull-rom", "lanczos3"
image_filter = "triangle"

[tasks]
image_bound = [0, 0]
