[editor]
scrolloff = 999
line-number = "relative"  
bufferline = "multiple" # shows bufferline when more than one buffer
mouse = false
end-of-line-diagnostics	= "hint"

[editor.lsp]
display-inlay-hints = true

# changes the cursor shape depending on the mode you're in. 
[editor.cursor-shape] 
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
 
[keys.insert]
j = { k = "normal_mode" }

[editor.indent-guides]
render = true
character = "."
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"
